language: ruby
sudo: false
rvm:
  - 2.2.0
  - 2.2.1
bundler_args: --without production
addons:
  postgresql: '9.4'
  code_climate:
    repo_token: c92b395b2001babc502763bde49a14affa65ee57d76106e9c77df566e30c9983
before_install:
  - gem update bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
notifications:
  email:
    - fatbulat5@gmail.com
branches:
  only:
    - master
env:
  global:
    secure: 0ac9da3766b5fe72a3a89243ae3bb60fde41c7d6ec2602e0bf9171f922ae24c59fa54fe1c4c650c801c59ca427e0cef7c0c110a371990ce35ca966f425d8bf1a
